# Capstone Assignment - Regression

<b>Description: </b>
The dataset contains 9568 datapoints regarding power output of the Combined Cycle Power Plant over 6 years (2006-2011). <br>
Features consist of hourly average ambient variables 
* Temperature (0) in the range 1.81°C and 37.11°C,
* Ambient Pressure (1) in the range 992.89-1033.30 milibar,
* Relative Humidity (2) in the range 25.56% to 100.16%
* Exhaust Vacuum (3) in teh range 25.36-81.56 cm Hg
* Net hourly electrical energy output (4) 420.26-495.76 MW

Objectives: -

<ul>
    <li>The dataset would require EDA</li>
    <li>Visualize the relationship between variables</li>
    <ol>
        <li>Pair plots</li>
        <li>Histograms and PDFs</li>
        <li>Scatter Plots</li>
    </ol>
    <li>Contruct a model to predict PE and select a set of variables for it</li>
    <li>Try various models from regression such as 
    <ol>
        <li>Linear OLS</li> 
        <li>GLM</li> 
        <li>Ridge</li> 
        <li>Lasso</li> 
        <li>SVR</li> 
    </ol>
    and arrive at the best model for the data in question.
</ul>

In [4]:
# Write your solution here
import numpy as np
import pandas as pd

dataset = pd.read_csv('../../../data/capstonedataset.csv')
dataset.head()

       0      1        2      3       4
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90